Parameters:
  VPCCidrBlock:
    Type: String
    Default: 10.0.0.0/16

  
Resources:    
  CentralVPC:    #creating VPC by the name of India     
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: !Ref VPCCidrBlock
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: VPCId
          Value: CentralVPC

  MainGW:         # Creating IGW by the name of MainGW
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: MainGW     

  VPCattachIGW:  # Attaching VPC to MainGW     
   Type: AWS::EC2::VPCGatewayAttachment
   Properties:
     InternetGatewayId: !Ref MainGW
     VpcId: !Ref CentralVPC
 
Outputs:
  CVPC:
   Description: A reference to  VPC 
   Value: !Ref CentralVPC
   Export:
     Name: VPCId
     
  
  MGW:
   Description: A ref to MainGW
   Value: !Ref MainGW 
   Export:
     Name: GId
     Value: !Ref MainGW 

  AGW:
   Description: A reference to VPCattachIGW 
   Value: !Ref VPCattachIGW
   Export:
     Name: AGWId
     
  